<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-SK3D42E8" failures="1" tests="6" name="com.BankingApp.TestCases.AddCustomerTestCases" time="2.969" errors="0" timestamp="2024-12-30T09:10:37 SAST" skipped="0">
  <testcase classname="com.BankingApp.TestCases.AddCustomerTestCases" name="VerifyBlankFields" time="0.425"/>
  <system-out/>
  <testcase classname="com.BankingApp.TestCases.AddCustomerTestCases" name="VerifyBlankFields" time="0.838"/>
  <system-out/>
  <testcase classname="com.BankingApp.TestCases.AddCustomerTestCases" name="VerifyBlankFields" time="0.643"/>
  <system-out/>
  <testcase classname="com.BankingApp.TestCases.AddCustomerTestCases" name="VerifyBlankFields" time="0.498">
    <failure message="The following asserts failed:
	 Unexpected alert message was diplayed  expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
 Unexpected alert message was diplayed  expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.BankingApp.TestCases.AddCustomerTestCases.VerifyBlankFields(AddCustomerTestCases.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- VerifyBlankFields -->
  <system-out/>
  <testcase classname="com.BankingApp.TestCases.AddCustomerTestCases" name="VerifyNewCustomer" time="0.369"/>
  <system-out/>
  <testcase classname="com.BankingApp.TestCases.AddCustomerTestCases" name="VerifyNameIsAdded" time="0.196"/>
  <system-out/>
</testsuite> <!-- com.BankingApp.TestCases.AddCustomerTestCases -->
